const data = [
  {
    id: 101,
    category: "Dessert",
    image: "https://www.themealdb.com/images/media/meals/tqtywx1468317395.jpg",
    price: 376,
    rating: 4.2,
    title: "Chocolate Gateau",
  },
  {
    id: 102,
    category: "Chicken",
    image: "https://www.themealdb.com/images/media/meals/qtuwxu1468233098.jpg",
    price: 365,
    rating: 3.1,
    title: "Chicken Enchilada Casserole",
  },
  {
    id: 103,
    category: "Starter",
    image: "https://www.themealdb.com/images/media/meals/wurrux1468416624.jpg",
    price: 379,
    rating: 3.3,
    title: "Cream Cheese Tart",
  },
  {
    id: 104,
    category: "Chicken",
    image: "https://www.themealdb.com/images/media/meals/ypxvwv1505333929.jpg",
    price: 430,
    rating: 4.3,
    title: "Crock Pot Chicken Baked Tacos",
  },
  {
    id: 105,
    category: "Chicken",
    image: "https://www.themealdb.com/images/media/meals/tyywsw1505930373.jpg",
    price: 431,
    rating: 2.9,
    title: "Chicken Karaage",
  },
  {
    id: 106,
    category: "Chicken",
    image: "https://www.themealdb.com/images/media/meals/qstyvs1505931190.jpg",
    price: 432,
    rating: 4.1,
    title: "Coq au vin",
  },
  {
    id: 107,
    category: "Pasta",
    image: "https://www.themealdb.com/images/media/meals/usywpp1511189717.jpg",
    price: 439,
    rating: 3.4,
    title: "Chilli prawn linguine",
  },
  {
    id: 108,
    category: "Starter",
    image: "https://www.themealdb.com/images/media/meals/rvtvuw1511190488.jpg",
    price: 440,
    rating: 4.6,
    title: "Clam chowder",
  },
  {
    id: 109,
    category: "Chicken",
    image: "https://www.themealdb.com/images/media/meals/uuuspp1511297945.jpg",
    price: 446,
    rating: 4.2,
    title: "Chicken & mushroom Hotpot",
  },
  {
    id: 110,
    category: "Dessert",
    image: "https://www.themealdb.com/images/media/meals/uttuxy1511382180.jpg",
    price: 453,
    rating: 3.2,
    title: "Chocolate Avocado Mousse",
  },
];

export default data;
